insert into Uloga values (10, 'Otelo', 'g', 'm');
insert into Uloga values (10, 'Jago', 'g', 'm');
insert into Uloga values (10, 'Dezdemona', 'g', 'z');
insert into Uloga values (10, 'Brabancio', 'g', 'm');
insert into Uloga values (10, 'Rodrigo', 's', 'm');
insert into Uloga values (10, 'Montano', 's', 'm');
insert into Uloga values (10, 'Gracijano', 's', 'm');
insert into Uloga values (20, 'Gospodjica', 'g', 'z');
insert into Uloga values (20, 'Otac', 'g', 'm');
insert into Uloga values (20, 'Jovanka', 'g', 'z');
insert into Uloga values (20, 'Dajdza Vlado Hadzi-Vasic', 'g', 'm');
insert into Uloga values (20, 'Majka', 's', 'z');
insert into Uloga values (30, 'Don Zuan', 'g', 'm');
insert into Uloga values (30, 'Zganare', 'g', 'm');
insert into Uloga values (30, 'Dona Elvira', 'g', 'z');
insert into Uloga values (30, 'Don Luis', 's', 'm');
insert into Uloga values (30, 'Don Karlos', 's', 'm');
insert into Uloga values (40, 'Lamberto Laudizi', 'g', 'm');
insert into Uloga values (40, 'Gospodja Frola', 'g', 'z');
insert into Uloga values (40, 'Savetnik Agaci', 'g', 'm');
insert into Uloga values (40, 'Gospodin Sireli', 's', 'm');
insert into Uloga values (50, 'Rodion Romanovic Raskoljnikov', 'g', 'm');
insert into Uloga values (50, 'Porfirij Petrovic', 'g', 'm');
insert into Uloga values (50, 'Sonja Marmeladova', 'g', 'z');
insert into Uloga values (50, 'Koh', 'g', 'm');
commit;